name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'

runs:
  using: 'composite'
  steps:
    - name: 📦 Setup pnpm and install
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v5
      with:
        node-version-file: "package.json"
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install
      shell: bash
